_BASE: ../OTAM_base.yaml
TASK_TYPE: few_shot_action
RANDOM_SEED: 18
SUPPORT_SHOT: 1
INIT_METHOD: tcp://localhost:1111
NUM_GPUS: 1
CUDA_VISIBLE_DEVICES: '1'
OUTPUT_DIR: output/finesports/1-shot

TRAIN:
  ENABLE: true
  AUTO_RESUME: true
  USE_CLASSIFICATION_VALUE: 3.5
  NUM_CLASS: 24
  DATASET: finesports
  META_BATCH: true
  WAY: 5
  SHOT: 1
  QUERY_PER_CLASS: 4
  QUERY_PER_CLASS_TEST: 1
  NUM_TRAIN_TASKS: 10000
  NUM_TEST_TASKS: 1000
  VAL_FRE_ITER: 1000
  BATCH_SIZE: 1
  BATCH_SIZE_PER_TASK: 1
  #CHECKPOINT_FILE_PATH: ""
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  NUM_FOLDS: 1
  USE_TRAJ: true

TRAJ:
  LAM: 0.1
  LBDA: 0.3
  DIM: 6
  MID_DIM: 256
  KEY: 'traj_seq'
  ROOT: '/Datasets/Traj/traj_npz_yolo/finesports'
  KEEP_SUBDIR: False
  NORM_DIST: false
  #NORM_MODE: 'zscore'


AUGMENTATION:
  COLOR_AUG: false
  NO_RANDOM_ERASE: true
  SUPPORT_QUERY_DIFF: true

TEST:
  ENABLE: false
  DATASET: finesports
  SHOT: [1]
  BATCH_SIZE: 1
  TEST_SET: val
  NUM_ENSEMBLE_VIEWS: 1
  SPATIAL_CROPS: cctltr
  AUTOMATIC_MULTI_SCALE_TEST: false
  UPLOAD_CLASSIFIER_RESULTS: true


DATA:
  DATA_ROOT_DIR: /Datasets/FineSports_video
  ANNO_DIR: config/finesports/
  NUM_INPUT_FRAMES: 4
  SAMPLING_RATE: 4
  SAMPLING_UNIFORM: false
  TRAIN_JITTER_SCALES: [256, 256]
  MEAN: [0.48145466, 0.4578275, 0.40821073]
  STD: [0.26862954, 0.26130258, 0.27577711]
  TRAIN_CROP_SIZE: 112
  TEST_CROP_SIZE: 112
  TEST_SCALE: 256
  TEST_CENTER_CROP: true
  CLIP_INTERVAL: 8
  FPS: 12
  TARGET_FPS: 12

LOG_PERIOD: 50
SOLVER:
  BASE_LR: 0.001
  LR_POLICY: steps_with_relative_lrs
  STEPS_ITER: 1000
  STEPS: [0, 3, 5, 7]
  LRS: [1, 0.5, 0.1, 0.01]
  MAX_EPOCH: 10
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.5
  WARMUP_EPOCHS: 1
  WARMUP_START_LR: 1e-5
  OPTIM_METHOD: adamw
  DAMPENING: 0.0
  NESTEROV: true

ADAPTER:
  NAME: ViT_CLIP
  PRETRAINED: ViT-B/16
  WIDTH: 768
  PATCH_SIZE: 16
  LAYERS: 12
  HEADS: 12
  ADAPTER_SCALE: 0.25

